apiVersion: v1
kind: ConfigMap
metadata:
    name: log-config
data:
  # chaves com valores de propriedades; cada chave mapeia para um valor avulso
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  log_level: "DEBUG"
  # chaves semelhantes a fragmentos de arquivos
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=10    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
