apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: kuard-data
      hostPath:
        path: /var/lib/kuard
    - name: config-vol
      configMap:
        name: log-config

  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuard
      env:
        - name: LOG_LEVEL
          valueFrom:
           configMapKeyRef:
             name: log-config
             key: log_level
      volumeMounts:
        - mountPath: /data
          name: kuard-data
        - mountPath: /config
          name: config-vol
          readOnly: true
      resources:
        limits:
          cpu: "200m"
          memory: "1000Mi"
        requests:
          cpu: "100m"
          memory: "600Mi"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
